name: m7tas
version: '1.0-SNAPSHOT'
main: plugin.M7tas
api-version: '1.21'

commands:
  setup:
    description: Clear all classes and spawn them
    usage: /setup
  spectate:
    description: Spectate a class
    usage: /spectate <Archer|Berserk|Healer|Mage|Tank>
  unspectate:
    description: Stop spectating a class
    usage: /unspectate
  tas:
    description: Begin TAS
    usage: /tas
  reset:
    description: Resets all classes to their spawn locations
    usage: /reset
  simulate:
    description: Simulates movement (either walking or bonzo staff)
    usage: /simulate <move|bonzo> <x> <y> <z> <duration>

depend:
  - SkyBlockInVanilla