---
name: Issue
description: Do not create issues here regarding the queue system on mc.strad.dev
body:
  - type: checkboxes
    id: acknowledge
    attributes:
      label: Before you submit
      options:
        - label: I confirm that this is NOT a bug regarding the queue system on mc.strad.dev
          required: true
---


